services:
    c_foodapi:
        container_name: c_foodApi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:8080
        restart: always

             